"""Initial migration

Revision ID: 73b22ccbe472
Revises: 1ed43776064f
Create Date: 2017-04-24 09:08:30.923731

"""


# revision identifiers, used by Alembic.
revision = '73b22ccbe472'
down_revision = '1ed43776064f'
branch_labels = ('attendee_tournaments',)
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendee_tournament',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('first_name', sa.Unicode(), server_default='', nullable=False),
    sa.Column('last_name', sa.Unicode(), server_default='', nullable=False),
    sa.Column('email', sa.Unicode(), server_default='', nullable=False),
    sa.Column('cellphone', sa.Unicode(), server_default='', nullable=False),
    sa.Column('game', sa.Unicode(), server_default='', nullable=False),
    sa.Column('availability', sa.Unicode(), server_default='', nullable=False),
    sa.Column('format', sa.Unicode(), server_default='', nullable=False),
    sa.Column('experience', sa.Unicode(), server_default='', nullable=False),
    sa.Column('needs', sa.Unicode(), server_default='', nullable=False),
    sa.Column('why', sa.Unicode(), server_default='', nullable=False),
    sa.Column('volunteering', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('status', sa.Integer(), server_default='239694250', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendee_tournament'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendee_tournament')
    ### end Alembic commands ###
